### ISSUE TITLE
Deploy GraphQL Playground

### ISSUE THREAD

**Issue by schickling** [graphql-compose/graphql-compose-aws#1]
Would be great if you could also deploy the GraphQL Playground (additionally to GraphiQL) in your hosted demo! ✨

**Comment by nodkz** [comment]
Added 😉 Great tool!!! 👍
It was improved very well after my first look a couple month ago.

Pitty that it does not support:
- providing default query via url params (see url below)
- providing url param for auto-opening schema tab
Will be cool if add this features.

GraphiQL with default query:
https://graphql-compose.herokuapp.com/aws/?query=query%20%7B%0A%20%20aws(config%3A%20%7B%0A%20%20%20%20accessKeyId%3A%20%22---%3E%20YOUR_KEY%20%3C---%22%2C%0A%20%20%20%20secretAccessKey%3A%20%22---%3E%20YOUR_SECRET%20%3C---%22%2C%0A%20%20%7D)%20%0A%7D%0A%20%20%20%20%20%20

Playground without query:
https://graphql-compose.herokuapp.com/aws-playground?query=query%20%7B%0A%20%20aws(config%3A%20%7B%0A%20%20%20%20accessKeyId%3A%20%22---%3E%20YOUR_KEY%20%3C---%22%2C%0A%20%20%20%20secretAccessKey%3A%20%22---%3E%20YOUR_SECRET%20%3C---%22%2C%0A%20%20%7D)%20%0A%7D%0A%20%20%20%20%20%20

2017-12-03 22:41 GMT+06:00 Johannes Schickling <notifications@github.com>:

**Comment by schickling** [comment]
Can you create an issue (or even better a PR) for that [over here](https://github.com/graphcool/graphql-playground/issues)?
