### ISSUE TITLE
Deployment documentation

### ISSUE THREAD

**Issue by Code0x58** [graphql-compose/graphql-compose-aws#2]
Hey! This looks like it could be pretty cool, but I'm new to both Node, and haven't managed to get the demo running anywhere (e.g. various versions of the node Docker image with things like `NODE_OPTIONS=--experimental-modules` and attempts at tinkering - I feel I'm miles off).

I'm thinking that this could be deployed to an EC2 instance or ECS task with an IAM role applied, so keys aren't needed. If there was a public Dockerfile+image this, I think that'd be a great start for someone like me.

If this sounds sane, I'd be happy to help however I can, like adding to documentation after getting some experience with deployments, and looking at making a Cloudformation template.

**Comment by nodkz** [comment]
Please take a look on the following fork
https://github.com/lalyos/graphql-compose-aws

I think it's precisely what you need. Or it may be a good starting point ;)

**Comment by Code0x58** [comment]
Great, thanks!

Is there anything that'd stop this kind of thing getting accepted in a PR?

I'll have a read through the fork in the next few days.

**Comment by nodkz** [comment]
No rules no borders for great features and improvements.
Feel free to open PR with your code and we think what to do further ;)
